### ISSUE TITLE
Undeployment with outputs causes data error

### ISSUE THREAD

**Issue by alexmaslenn** [SODALITE-EU/xopera-rest-api#124]
When a blueprint that contains outputs section that references some attribute, e.g.
```yaml
  outputs:

    public_ip:
      description: The public IP of the provisioned VM
      type: string
      value: {get_attribute: [my-workstation, public_address]}
```
is undeployed, an error `opera.error.DataError: Cannot use an unset value: public_address` occurs since node is deleted and attribute value is unavailable.

 Since it is not clear, whether there is a scenario when outputs should be used after undemployment, no outputs should be evaluated after undemployment.
